/* soapH.h
   Generated by gSOAP 2.7.16 from testExample.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#define soap_write_LONG64(soap, data) ( soap_begin_send(soap) || soap_put_LONG64(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);

#define soap_read_LONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_LONG64(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#define soap_write_float(soap, data) ( soap_begin_send(soap) || soap_put_float(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);

#define soap_read_float(soap, data) ( soap_begin_recv(soap) || !soap_get_float(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#define soap_write_double(soap, data) ( soap_begin_send(soap) || soap_put_double(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);

#define soap_read_double(soap, data) ( soap_begin_recv(soap) || !soap_get_double(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#define soap_write_bool(soap, data) ( soap_begin_send(soap) || soap_put_bool(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);

#define soap_read_bool(soap, data) ( soap_begin_recv(soap) || !soap_get_bool(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);

#ifndef SOAP_TYPE__ns1__outercomplexGsoap5
#define SOAP_TYPE__ns1__outercomplexGsoap5 (37)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__outercomplexGsoap5(struct soap*, const char*, int, const _ns1__outercomplexGsoap5 *, const char*);
SOAP_FMAC3 _ns1__outercomplexGsoap5 * SOAP_FMAC4 soap_in__ns1__outercomplexGsoap5(struct soap*, const char*, _ns1__outercomplexGsoap5 *, const char*);

#define soap_write__ns1__outercomplexGsoap5(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__outercomplexGsoap5(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__outercomplexGsoap5(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__outercomplexGsoap5 * SOAP_FMAC4 soap_get__ns1__outercomplexGsoap5(struct soap*, _ns1__outercomplexGsoap5 *, const char*, const char*);

#define soap_new__ns1__outercomplexGsoap5(soap, n) soap_instantiate__ns1__outercomplexGsoap5(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__outercomplexGsoap5(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__outercomplexGsoap5 * SOAP_FMAC2 soap_instantiate__ns1__outercomplexGsoap5(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__outercomplexGsoap5(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__outercomplexGsoap4
#define SOAP_TYPE__ns1__outercomplexGsoap4 (36)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__outercomplexGsoap4(struct soap*, const char*, int, const _ns1__outercomplexGsoap4 *, const char*);
SOAP_FMAC3 _ns1__outercomplexGsoap4 * SOAP_FMAC4 soap_in__ns1__outercomplexGsoap4(struct soap*, const char*, _ns1__outercomplexGsoap4 *, const char*);

#define soap_write__ns1__outercomplexGsoap4(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__outercomplexGsoap4(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__outercomplexGsoap4(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__outercomplexGsoap4 * SOAP_FMAC4 soap_get__ns1__outercomplexGsoap4(struct soap*, _ns1__outercomplexGsoap4 *, const char*, const char*);

#define soap_new__ns1__outercomplexGsoap4(soap, n) soap_instantiate__ns1__outercomplexGsoap4(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__outercomplexGsoap4(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__outercomplexGsoap4 * SOAP_FMAC2 soap_instantiate__ns1__outercomplexGsoap4(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__outercomplexGsoap4(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__outercomplexGsoap3
#define SOAP_TYPE__ns1__outercomplexGsoap3 (35)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__outercomplexGsoap3(struct soap*, const char*, int, const _ns1__outercomplexGsoap3 *, const char*);
SOAP_FMAC3 _ns1__outercomplexGsoap3 * SOAP_FMAC4 soap_in__ns1__outercomplexGsoap3(struct soap*, const char*, _ns1__outercomplexGsoap3 *, const char*);

#define soap_write__ns1__outercomplexGsoap3(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__outercomplexGsoap3(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__outercomplexGsoap3(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__outercomplexGsoap3 * SOAP_FMAC4 soap_get__ns1__outercomplexGsoap3(struct soap*, _ns1__outercomplexGsoap3 *, const char*, const char*);

#define soap_new__ns1__outercomplexGsoap3(soap, n) soap_instantiate__ns1__outercomplexGsoap3(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__outercomplexGsoap3(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__outercomplexGsoap3 * SOAP_FMAC2 soap_instantiate__ns1__outercomplexGsoap3(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__outercomplexGsoap3(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__outercomplexGsoap2
#define SOAP_TYPE__ns1__outercomplexGsoap2 (34)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__outercomplexGsoap2(struct soap*, const char*, int, const _ns1__outercomplexGsoap2 *, const char*);
SOAP_FMAC3 _ns1__outercomplexGsoap2 * SOAP_FMAC4 soap_in__ns1__outercomplexGsoap2(struct soap*, const char*, _ns1__outercomplexGsoap2 *, const char*);

#define soap_write__ns1__outercomplexGsoap2(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__outercomplexGsoap2(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__outercomplexGsoap2(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__outercomplexGsoap2 * SOAP_FMAC4 soap_get__ns1__outercomplexGsoap2(struct soap*, _ns1__outercomplexGsoap2 *, const char*, const char*);

#define soap_new__ns1__outercomplexGsoap2(soap, n) soap_instantiate__ns1__outercomplexGsoap2(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__outercomplexGsoap2(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__outercomplexGsoap2 * SOAP_FMAC2 soap_instantiate__ns1__outercomplexGsoap2(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__outercomplexGsoap2(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__outercomplexGsoap1
#define SOAP_TYPE__ns1__outercomplexGsoap1 (33)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__outercomplexGsoap1(struct soap*, const char*, int, const _ns1__outercomplexGsoap1 *, const char*);
SOAP_FMAC3 _ns1__outercomplexGsoap1 * SOAP_FMAC4 soap_in__ns1__outercomplexGsoap1(struct soap*, const char*, _ns1__outercomplexGsoap1 *, const char*);

#define soap_write__ns1__outercomplexGsoap1(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__outercomplexGsoap1(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__outercomplexGsoap1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__outercomplexGsoap1 * SOAP_FMAC4 soap_get__ns1__outercomplexGsoap1(struct soap*, _ns1__outercomplexGsoap1 *, const char*, const char*);

#define soap_new__ns1__outercomplexGsoap1(soap, n) soap_instantiate__ns1__outercomplexGsoap1(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__outercomplexGsoap1(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__outercomplexGsoap1 * SOAP_FMAC2 soap_instantiate__ns1__outercomplexGsoap1(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__outercomplexGsoap1(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__outersimpleGsoap10
#define SOAP_TYPE__ns1__outersimpleGsoap10 (32)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__outersimpleGsoap10(struct soap*, const char*, int, const _ns1__outersimpleGsoap10 *, const char*);
SOAP_FMAC3 _ns1__outersimpleGsoap10 * SOAP_FMAC4 soap_in__ns1__outersimpleGsoap10(struct soap*, const char*, _ns1__outersimpleGsoap10 *, const char*);

#define soap_write__ns1__outersimpleGsoap10(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__outersimpleGsoap10(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__outersimpleGsoap10(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__outersimpleGsoap10 * SOAP_FMAC4 soap_get__ns1__outersimpleGsoap10(struct soap*, _ns1__outersimpleGsoap10 *, const char*, const char*);

#define soap_new__ns1__outersimpleGsoap10(soap, n) soap_instantiate__ns1__outersimpleGsoap10(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__outersimpleGsoap10(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__outersimpleGsoap10 * SOAP_FMAC2 soap_instantiate__ns1__outersimpleGsoap10(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__outersimpleGsoap10(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__outersimpleGsoap8
#define SOAP_TYPE__ns1__outersimpleGsoap8 (31)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__outersimpleGsoap8(struct soap*, const char*, int, const _ns1__outersimpleGsoap8 *, const char*);
SOAP_FMAC3 _ns1__outersimpleGsoap8 * SOAP_FMAC4 soap_in__ns1__outersimpleGsoap8(struct soap*, const char*, _ns1__outersimpleGsoap8 *, const char*);

#define soap_write__ns1__outersimpleGsoap8(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__outersimpleGsoap8(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__outersimpleGsoap8(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__outersimpleGsoap8 * SOAP_FMAC4 soap_get__ns1__outersimpleGsoap8(struct soap*, _ns1__outersimpleGsoap8 *, const char*, const char*);

#define soap_new__ns1__outersimpleGsoap8(soap, n) soap_instantiate__ns1__outersimpleGsoap8(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__outersimpleGsoap8(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__outersimpleGsoap8 * SOAP_FMAC2 soap_instantiate__ns1__outersimpleGsoap8(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__outersimpleGsoap8(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__outersimpleGsoap6
#define SOAP_TYPE__ns1__outersimpleGsoap6 (30)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__outersimpleGsoap6(struct soap*, const char*, int, const _ns1__outersimpleGsoap6 *, const char*);
SOAP_FMAC3 _ns1__outersimpleGsoap6 * SOAP_FMAC4 soap_in__ns1__outersimpleGsoap6(struct soap*, const char*, _ns1__outersimpleGsoap6 *, const char*);

#define soap_write__ns1__outersimpleGsoap6(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__outersimpleGsoap6(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__outersimpleGsoap6(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__outersimpleGsoap6 * SOAP_FMAC4 soap_get__ns1__outersimpleGsoap6(struct soap*, _ns1__outersimpleGsoap6 *, const char*, const char*);

#define soap_new__ns1__outersimpleGsoap6(soap, n) soap_instantiate__ns1__outersimpleGsoap6(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__outersimpleGsoap6(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__outersimpleGsoap6 * SOAP_FMAC2 soap_instantiate__ns1__outersimpleGsoap6(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__outersimpleGsoap6(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__outersimpleGsoap4
#define SOAP_TYPE__ns1__outersimpleGsoap4 (29)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__outersimpleGsoap4(struct soap*, const char*, int, const _ns1__outersimpleGsoap4 *, const char*);
SOAP_FMAC3 _ns1__outersimpleGsoap4 * SOAP_FMAC4 soap_in__ns1__outersimpleGsoap4(struct soap*, const char*, _ns1__outersimpleGsoap4 *, const char*);

#define soap_write__ns1__outersimpleGsoap4(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__outersimpleGsoap4(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__outersimpleGsoap4(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__outersimpleGsoap4 * SOAP_FMAC4 soap_get__ns1__outersimpleGsoap4(struct soap*, _ns1__outersimpleGsoap4 *, const char*, const char*);

#define soap_new__ns1__outersimpleGsoap4(soap, n) soap_instantiate__ns1__outersimpleGsoap4(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__outersimpleGsoap4(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__outersimpleGsoap4 * SOAP_FMAC2 soap_instantiate__ns1__outersimpleGsoap4(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__outersimpleGsoap4(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__outersimpleGsoap2
#define SOAP_TYPE__ns1__outersimpleGsoap2 (28)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__outersimpleGsoap2(struct soap*, const char*, int, const _ns1__outersimpleGsoap2 *, const char*);
SOAP_FMAC3 _ns1__outersimpleGsoap2 * SOAP_FMAC4 soap_in__ns1__outersimpleGsoap2(struct soap*, const char*, _ns1__outersimpleGsoap2 *, const char*);

#define soap_write__ns1__outersimpleGsoap2(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__outersimpleGsoap2(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__outersimpleGsoap2(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__outersimpleGsoap2 * SOAP_FMAC4 soap_get__ns1__outersimpleGsoap2(struct soap*, _ns1__outersimpleGsoap2 *, const char*, const char*);

#define soap_new__ns1__outersimpleGsoap2(soap, n) soap_instantiate__ns1__outersimpleGsoap2(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__outersimpleGsoap2(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__outersimpleGsoap2 * SOAP_FMAC2 soap_instantiate__ns1__outersimpleGsoap2(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__outersimpleGsoap2(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__complexGsoap10
#define SOAP_TYPE__ns1__complexGsoap10 (27)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__complexGsoap10(struct soap*, const char*, int, const _ns1__complexGsoap10 *, const char*);
SOAP_FMAC3 _ns1__complexGsoap10 * SOAP_FMAC4 soap_in__ns1__complexGsoap10(struct soap*, const char*, _ns1__complexGsoap10 *, const char*);

#define soap_write__ns1__complexGsoap10(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__complexGsoap10(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__complexGsoap10(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__complexGsoap10 * SOAP_FMAC4 soap_get__ns1__complexGsoap10(struct soap*, _ns1__complexGsoap10 *, const char*, const char*);

#define soap_new__ns1__complexGsoap10(soap, n) soap_instantiate__ns1__complexGsoap10(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__complexGsoap10(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__complexGsoap10 * SOAP_FMAC2 soap_instantiate__ns1__complexGsoap10(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__complexGsoap10(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__complexGsoap8
#define SOAP_TYPE__ns1__complexGsoap8 (26)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__complexGsoap8(struct soap*, const char*, int, const _ns1__complexGsoap8 *, const char*);
SOAP_FMAC3 _ns1__complexGsoap8 * SOAP_FMAC4 soap_in__ns1__complexGsoap8(struct soap*, const char*, _ns1__complexGsoap8 *, const char*);

#define soap_write__ns1__complexGsoap8(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__complexGsoap8(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__complexGsoap8(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__complexGsoap8 * SOAP_FMAC4 soap_get__ns1__complexGsoap8(struct soap*, _ns1__complexGsoap8 *, const char*, const char*);

#define soap_new__ns1__complexGsoap8(soap, n) soap_instantiate__ns1__complexGsoap8(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__complexGsoap8(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__complexGsoap8 * SOAP_FMAC2 soap_instantiate__ns1__complexGsoap8(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__complexGsoap8(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__complexGsoap6
#define SOAP_TYPE__ns1__complexGsoap6 (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__complexGsoap6(struct soap*, const char*, int, const _ns1__complexGsoap6 *, const char*);
SOAP_FMAC3 _ns1__complexGsoap6 * SOAP_FMAC4 soap_in__ns1__complexGsoap6(struct soap*, const char*, _ns1__complexGsoap6 *, const char*);

#define soap_write__ns1__complexGsoap6(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__complexGsoap6(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__complexGsoap6(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__complexGsoap6 * SOAP_FMAC4 soap_get__ns1__complexGsoap6(struct soap*, _ns1__complexGsoap6 *, const char*, const char*);

#define soap_new__ns1__complexGsoap6(soap, n) soap_instantiate__ns1__complexGsoap6(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__complexGsoap6(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__complexGsoap6 * SOAP_FMAC2 soap_instantiate__ns1__complexGsoap6(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__complexGsoap6(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__complexGsoap4
#define SOAP_TYPE__ns1__complexGsoap4 (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__complexGsoap4(struct soap*, const char*, int, const _ns1__complexGsoap4 *, const char*);
SOAP_FMAC3 _ns1__complexGsoap4 * SOAP_FMAC4 soap_in__ns1__complexGsoap4(struct soap*, const char*, _ns1__complexGsoap4 *, const char*);

#define soap_write__ns1__complexGsoap4(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__complexGsoap4(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__complexGsoap4(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__complexGsoap4 * SOAP_FMAC4 soap_get__ns1__complexGsoap4(struct soap*, _ns1__complexGsoap4 *, const char*, const char*);

#define soap_new__ns1__complexGsoap4(soap, n) soap_instantiate__ns1__complexGsoap4(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__complexGsoap4(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__complexGsoap4 * SOAP_FMAC2 soap_instantiate__ns1__complexGsoap4(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__complexGsoap4(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__complexGsoap2
#define SOAP_TYPE__ns1__complexGsoap2 (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__complexGsoap2(struct soap*, const char*, int, const _ns1__complexGsoap2 *, const char*);
SOAP_FMAC3 _ns1__complexGsoap2 * SOAP_FMAC4 soap_in__ns1__complexGsoap2(struct soap*, const char*, _ns1__complexGsoap2 *, const char*);

#define soap_write__ns1__complexGsoap2(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__complexGsoap2(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__complexGsoap2(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__complexGsoap2 * SOAP_FMAC4 soap_get__ns1__complexGsoap2(struct soap*, _ns1__complexGsoap2 *, const char*, const char*);

#define soap_new__ns1__complexGsoap2(soap, n) soap_instantiate__ns1__complexGsoap2(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__complexGsoap2(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__complexGsoap2 * SOAP_FMAC2 soap_instantiate__ns1__complexGsoap2(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__complexGsoap2(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__simpleGsoap50
#define SOAP_TYPE__ns1__simpleGsoap50 (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__simpleGsoap50(struct soap*, const char*, int, const _ns1__simpleGsoap50 *, const char*);
SOAP_FMAC3 _ns1__simpleGsoap50 * SOAP_FMAC4 soap_in__ns1__simpleGsoap50(struct soap*, const char*, _ns1__simpleGsoap50 *, const char*);

#define soap_write__ns1__simpleGsoap50(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__simpleGsoap50(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__simpleGsoap50(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__simpleGsoap50 * SOAP_FMAC4 soap_get__ns1__simpleGsoap50(struct soap*, _ns1__simpleGsoap50 *, const char*, const char*);

#define soap_new__ns1__simpleGsoap50(soap, n) soap_instantiate__ns1__simpleGsoap50(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__simpleGsoap50(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__simpleGsoap50 * SOAP_FMAC2 soap_instantiate__ns1__simpleGsoap50(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__simpleGsoap50(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__simpleGsoap40
#define SOAP_TYPE__ns1__simpleGsoap40 (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__simpleGsoap40(struct soap*, const char*, int, const _ns1__simpleGsoap40 *, const char*);
SOAP_FMAC3 _ns1__simpleGsoap40 * SOAP_FMAC4 soap_in__ns1__simpleGsoap40(struct soap*, const char*, _ns1__simpleGsoap40 *, const char*);

#define soap_write__ns1__simpleGsoap40(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__simpleGsoap40(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__simpleGsoap40(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__simpleGsoap40 * SOAP_FMAC4 soap_get__ns1__simpleGsoap40(struct soap*, _ns1__simpleGsoap40 *, const char*, const char*);

#define soap_new__ns1__simpleGsoap40(soap, n) soap_instantiate__ns1__simpleGsoap40(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__simpleGsoap40(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__simpleGsoap40 * SOAP_FMAC2 soap_instantiate__ns1__simpleGsoap40(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__simpleGsoap40(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__simpleGsoap30
#define SOAP_TYPE__ns1__simpleGsoap30 (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__simpleGsoap30(struct soap*, const char*, int, const _ns1__simpleGsoap30 *, const char*);
SOAP_FMAC3 _ns1__simpleGsoap30 * SOAP_FMAC4 soap_in__ns1__simpleGsoap30(struct soap*, const char*, _ns1__simpleGsoap30 *, const char*);

#define soap_write__ns1__simpleGsoap30(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__simpleGsoap30(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__simpleGsoap30(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__simpleGsoap30 * SOAP_FMAC4 soap_get__ns1__simpleGsoap30(struct soap*, _ns1__simpleGsoap30 *, const char*, const char*);

#define soap_new__ns1__simpleGsoap30(soap, n) soap_instantiate__ns1__simpleGsoap30(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__simpleGsoap30(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__simpleGsoap30 * SOAP_FMAC2 soap_instantiate__ns1__simpleGsoap30(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__simpleGsoap30(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__simpleGsoap20
#define SOAP_TYPE__ns1__simpleGsoap20 (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__simpleGsoap20(struct soap*, const char*, int, const _ns1__simpleGsoap20 *, const char*);
SOAP_FMAC3 _ns1__simpleGsoap20 * SOAP_FMAC4 soap_in__ns1__simpleGsoap20(struct soap*, const char*, _ns1__simpleGsoap20 *, const char*);

#define soap_write__ns1__simpleGsoap20(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__simpleGsoap20(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__simpleGsoap20(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__simpleGsoap20 * SOAP_FMAC4 soap_get__ns1__simpleGsoap20(struct soap*, _ns1__simpleGsoap20 *, const char*, const char*);

#define soap_new__ns1__simpleGsoap20(soap, n) soap_instantiate__ns1__simpleGsoap20(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__simpleGsoap20(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__simpleGsoap20 * SOAP_FMAC2 soap_instantiate__ns1__simpleGsoap20(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__simpleGsoap20(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__simpleGsoap10
#define SOAP_TYPE__ns1__simpleGsoap10 (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__simpleGsoap10(struct soap*, const char*, int, const _ns1__simpleGsoap10 *, const char*);
SOAP_FMAC3 _ns1__simpleGsoap10 * SOAP_FMAC4 soap_in__ns1__simpleGsoap10(struct soap*, const char*, _ns1__simpleGsoap10 *, const char*);

#define soap_write__ns1__simpleGsoap10(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__simpleGsoap10(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__simpleGsoap10(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__simpleGsoap10 * SOAP_FMAC4 soap_get__ns1__simpleGsoap10(struct soap*, _ns1__simpleGsoap10 *, const char*, const char*);

#define soap_new__ns1__simpleGsoap10(soap, n) soap_instantiate__ns1__simpleGsoap10(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__simpleGsoap10(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__simpleGsoap10 * SOAP_FMAC2 soap_instantiate__ns1__simpleGsoap10(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__simpleGsoap10(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__innercomplexGsoap5
#define SOAP_TYPE_ns1__innercomplexGsoap5 (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__innercomplexGsoap5(struct soap*, const char*, int, const ns1__innercomplexGsoap5 *, const char*);
SOAP_FMAC3 ns1__innercomplexGsoap5 * SOAP_FMAC4 soap_in_ns1__innercomplexGsoap5(struct soap*, const char*, ns1__innercomplexGsoap5 *, const char*);

#define soap_write_ns1__innercomplexGsoap5(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns1__innercomplexGsoap5(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__innercomplexGsoap5(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innercomplexGsoap5 * SOAP_FMAC4 soap_get_ns1__innercomplexGsoap5(struct soap*, ns1__innercomplexGsoap5 *, const char*, const char*);

#define soap_new_ns1__innercomplexGsoap5(soap, n) soap_instantiate_ns1__innercomplexGsoap5(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__innercomplexGsoap5(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__innercomplexGsoap5 * SOAP_FMAC2 soap_instantiate_ns1__innercomplexGsoap5(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__innercomplexGsoap5(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__innercomplexGsoap4
#define SOAP_TYPE_ns1__innercomplexGsoap4 (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__innercomplexGsoap4(struct soap*, const char*, int, const ns1__innercomplexGsoap4 *, const char*);
SOAP_FMAC3 ns1__innercomplexGsoap4 * SOAP_FMAC4 soap_in_ns1__innercomplexGsoap4(struct soap*, const char*, ns1__innercomplexGsoap4 *, const char*);

#define soap_write_ns1__innercomplexGsoap4(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns1__innercomplexGsoap4(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__innercomplexGsoap4(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innercomplexGsoap4 * SOAP_FMAC4 soap_get_ns1__innercomplexGsoap4(struct soap*, ns1__innercomplexGsoap4 *, const char*, const char*);

#define soap_new_ns1__innercomplexGsoap4(soap, n) soap_instantiate_ns1__innercomplexGsoap4(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__innercomplexGsoap4(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__innercomplexGsoap4 * SOAP_FMAC2 soap_instantiate_ns1__innercomplexGsoap4(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__innercomplexGsoap4(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__innercomplexGsoap3
#define SOAP_TYPE_ns1__innercomplexGsoap3 (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__innercomplexGsoap3(struct soap*, const char*, int, const ns1__innercomplexGsoap3 *, const char*);
SOAP_FMAC3 ns1__innercomplexGsoap3 * SOAP_FMAC4 soap_in_ns1__innercomplexGsoap3(struct soap*, const char*, ns1__innercomplexGsoap3 *, const char*);

#define soap_write_ns1__innercomplexGsoap3(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns1__innercomplexGsoap3(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__innercomplexGsoap3(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innercomplexGsoap3 * SOAP_FMAC4 soap_get_ns1__innercomplexGsoap3(struct soap*, ns1__innercomplexGsoap3 *, const char*, const char*);

#define soap_new_ns1__innercomplexGsoap3(soap, n) soap_instantiate_ns1__innercomplexGsoap3(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__innercomplexGsoap3(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__innercomplexGsoap3 * SOAP_FMAC2 soap_instantiate_ns1__innercomplexGsoap3(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__innercomplexGsoap3(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__innercomplexGsoap2
#define SOAP_TYPE_ns1__innercomplexGsoap2 (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__innercomplexGsoap2(struct soap*, const char*, int, const ns1__innercomplexGsoap2 *, const char*);
SOAP_FMAC3 ns1__innercomplexGsoap2 * SOAP_FMAC4 soap_in_ns1__innercomplexGsoap2(struct soap*, const char*, ns1__innercomplexGsoap2 *, const char*);

#define soap_write_ns1__innercomplexGsoap2(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns1__innercomplexGsoap2(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__innercomplexGsoap2(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innercomplexGsoap2 * SOAP_FMAC4 soap_get_ns1__innercomplexGsoap2(struct soap*, ns1__innercomplexGsoap2 *, const char*, const char*);

#define soap_new_ns1__innercomplexGsoap2(soap, n) soap_instantiate_ns1__innercomplexGsoap2(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__innercomplexGsoap2(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__innercomplexGsoap2 * SOAP_FMAC2 soap_instantiate_ns1__innercomplexGsoap2(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__innercomplexGsoap2(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__innercomplexGsoap1
#define SOAP_TYPE_ns1__innercomplexGsoap1 (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__innercomplexGsoap1(struct soap*, const char*, int, const ns1__innercomplexGsoap1 *, const char*);
SOAP_FMAC3 ns1__innercomplexGsoap1 * SOAP_FMAC4 soap_in_ns1__innercomplexGsoap1(struct soap*, const char*, ns1__innercomplexGsoap1 *, const char*);

#define soap_write_ns1__innercomplexGsoap1(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns1__innercomplexGsoap1(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__innercomplexGsoap1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innercomplexGsoap1 * SOAP_FMAC4 soap_get_ns1__innercomplexGsoap1(struct soap*, ns1__innercomplexGsoap1 *, const char*, const char*);

#define soap_new_ns1__innercomplexGsoap1(soap, n) soap_instantiate_ns1__innercomplexGsoap1(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__innercomplexGsoap1(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__innercomplexGsoap1 * SOAP_FMAC2 soap_instantiate_ns1__innercomplexGsoap1(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__innercomplexGsoap1(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__innersimpleGsoap10
#define SOAP_TYPE_ns1__innersimpleGsoap10 (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__innersimpleGsoap10(struct soap*, const char*, int, const ns1__innersimpleGsoap10 *, const char*);
SOAP_FMAC3 ns1__innersimpleGsoap10 * SOAP_FMAC4 soap_in_ns1__innersimpleGsoap10(struct soap*, const char*, ns1__innersimpleGsoap10 *, const char*);

#define soap_write_ns1__innersimpleGsoap10(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns1__innersimpleGsoap10(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__innersimpleGsoap10(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innersimpleGsoap10 * SOAP_FMAC4 soap_get_ns1__innersimpleGsoap10(struct soap*, ns1__innersimpleGsoap10 *, const char*, const char*);

#define soap_new_ns1__innersimpleGsoap10(soap, n) soap_instantiate_ns1__innersimpleGsoap10(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__innersimpleGsoap10(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__innersimpleGsoap10 * SOAP_FMAC2 soap_instantiate_ns1__innersimpleGsoap10(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__innersimpleGsoap10(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__innersimpleGsoap8
#define SOAP_TYPE_ns1__innersimpleGsoap8 (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__innersimpleGsoap8(struct soap*, const char*, int, const ns1__innersimpleGsoap8 *, const char*);
SOAP_FMAC3 ns1__innersimpleGsoap8 * SOAP_FMAC4 soap_in_ns1__innersimpleGsoap8(struct soap*, const char*, ns1__innersimpleGsoap8 *, const char*);

#define soap_write_ns1__innersimpleGsoap8(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns1__innersimpleGsoap8(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__innersimpleGsoap8(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innersimpleGsoap8 * SOAP_FMAC4 soap_get_ns1__innersimpleGsoap8(struct soap*, ns1__innersimpleGsoap8 *, const char*, const char*);

#define soap_new_ns1__innersimpleGsoap8(soap, n) soap_instantiate_ns1__innersimpleGsoap8(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__innersimpleGsoap8(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__innersimpleGsoap8 * SOAP_FMAC2 soap_instantiate_ns1__innersimpleGsoap8(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__innersimpleGsoap8(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__innersimpleGsoap6
#define SOAP_TYPE_ns1__innersimpleGsoap6 (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__innersimpleGsoap6(struct soap*, const char*, int, const ns1__innersimpleGsoap6 *, const char*);
SOAP_FMAC3 ns1__innersimpleGsoap6 * SOAP_FMAC4 soap_in_ns1__innersimpleGsoap6(struct soap*, const char*, ns1__innersimpleGsoap6 *, const char*);

#define soap_write_ns1__innersimpleGsoap6(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns1__innersimpleGsoap6(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__innersimpleGsoap6(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innersimpleGsoap6 * SOAP_FMAC4 soap_get_ns1__innersimpleGsoap6(struct soap*, ns1__innersimpleGsoap6 *, const char*, const char*);

#define soap_new_ns1__innersimpleGsoap6(soap, n) soap_instantiate_ns1__innersimpleGsoap6(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__innersimpleGsoap6(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__innersimpleGsoap6 * SOAP_FMAC2 soap_instantiate_ns1__innersimpleGsoap6(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__innersimpleGsoap6(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__innersimpleGsoap4
#define SOAP_TYPE_ns1__innersimpleGsoap4 (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__innersimpleGsoap4(struct soap*, const char*, int, const ns1__innersimpleGsoap4 *, const char*);
SOAP_FMAC3 ns1__innersimpleGsoap4 * SOAP_FMAC4 soap_in_ns1__innersimpleGsoap4(struct soap*, const char*, ns1__innersimpleGsoap4 *, const char*);

#define soap_write_ns1__innersimpleGsoap4(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns1__innersimpleGsoap4(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__innersimpleGsoap4(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innersimpleGsoap4 * SOAP_FMAC4 soap_get_ns1__innersimpleGsoap4(struct soap*, ns1__innersimpleGsoap4 *, const char*, const char*);

#define soap_new_ns1__innersimpleGsoap4(soap, n) soap_instantiate_ns1__innersimpleGsoap4(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__innersimpleGsoap4(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__innersimpleGsoap4 * SOAP_FMAC2 soap_instantiate_ns1__innersimpleGsoap4(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__innersimpleGsoap4(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__innersimpleGsoap2
#define SOAP_TYPE_ns1__innersimpleGsoap2 (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__innersimpleGsoap2(struct soap*, const char*, int, const ns1__innersimpleGsoap2 *, const char*);
SOAP_FMAC3 ns1__innersimpleGsoap2 * SOAP_FMAC4 soap_in_ns1__innersimpleGsoap2(struct soap*, const char*, ns1__innersimpleGsoap2 *, const char*);

#define soap_write_ns1__innersimpleGsoap2(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns1__innersimpleGsoap2(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__innersimpleGsoap2(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innersimpleGsoap2 * SOAP_FMAC4 soap_get_ns1__innersimpleGsoap2(struct soap*, ns1__innersimpleGsoap2 *, const char*, const char*);

#define soap_new_ns1__innersimpleGsoap2(soap, n) soap_instantiate_ns1__innersimpleGsoap2(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__innersimpleGsoap2(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__innersimpleGsoap2 * SOAP_FMAC2 soap_instantiate_ns1__innersimpleGsoap2(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__innersimpleGsoap2(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons1__innercomplexGsoap5
#define SOAP_TYPE_PointerTons1__innercomplexGsoap5 (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__innercomplexGsoap5(struct soap*, ns1__innercomplexGsoap5 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__innercomplexGsoap5(struct soap*, const char *, int, ns1__innercomplexGsoap5 *const*, const char *);
SOAP_FMAC3 ns1__innercomplexGsoap5 ** SOAP_FMAC4 soap_in_PointerTons1__innercomplexGsoap5(struct soap*, const char*, ns1__innercomplexGsoap5 **, const char*);

#define soap_write_PointerTons1__innercomplexGsoap5(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__innercomplexGsoap5(soap, data), 0) || soap_put_PointerTons1__innercomplexGsoap5(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__innercomplexGsoap5(struct soap*, ns1__innercomplexGsoap5 *const*, const char*, const char*);

#define soap_read_PointerTons1__innercomplexGsoap5(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__innercomplexGsoap5(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innercomplexGsoap5 ** SOAP_FMAC4 soap_get_PointerTons1__innercomplexGsoap5(struct soap*, ns1__innercomplexGsoap5 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__innercomplexGsoap4
#define SOAP_TYPE_PointerTons1__innercomplexGsoap4 (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__innercomplexGsoap4(struct soap*, ns1__innercomplexGsoap4 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__innercomplexGsoap4(struct soap*, const char *, int, ns1__innercomplexGsoap4 *const*, const char *);
SOAP_FMAC3 ns1__innercomplexGsoap4 ** SOAP_FMAC4 soap_in_PointerTons1__innercomplexGsoap4(struct soap*, const char*, ns1__innercomplexGsoap4 **, const char*);

#define soap_write_PointerTons1__innercomplexGsoap4(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__innercomplexGsoap4(soap, data), 0) || soap_put_PointerTons1__innercomplexGsoap4(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__innercomplexGsoap4(struct soap*, ns1__innercomplexGsoap4 *const*, const char*, const char*);

#define soap_read_PointerTons1__innercomplexGsoap4(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__innercomplexGsoap4(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innercomplexGsoap4 ** SOAP_FMAC4 soap_get_PointerTons1__innercomplexGsoap4(struct soap*, ns1__innercomplexGsoap4 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__innercomplexGsoap3
#define SOAP_TYPE_PointerTons1__innercomplexGsoap3 (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__innercomplexGsoap3(struct soap*, ns1__innercomplexGsoap3 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__innercomplexGsoap3(struct soap*, const char *, int, ns1__innercomplexGsoap3 *const*, const char *);
SOAP_FMAC3 ns1__innercomplexGsoap3 ** SOAP_FMAC4 soap_in_PointerTons1__innercomplexGsoap3(struct soap*, const char*, ns1__innercomplexGsoap3 **, const char*);

#define soap_write_PointerTons1__innercomplexGsoap3(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__innercomplexGsoap3(soap, data), 0) || soap_put_PointerTons1__innercomplexGsoap3(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__innercomplexGsoap3(struct soap*, ns1__innercomplexGsoap3 *const*, const char*, const char*);

#define soap_read_PointerTons1__innercomplexGsoap3(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__innercomplexGsoap3(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innercomplexGsoap3 ** SOAP_FMAC4 soap_get_PointerTons1__innercomplexGsoap3(struct soap*, ns1__innercomplexGsoap3 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__innercomplexGsoap2
#define SOAP_TYPE_PointerTons1__innercomplexGsoap2 (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__innercomplexGsoap2(struct soap*, ns1__innercomplexGsoap2 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__innercomplexGsoap2(struct soap*, const char *, int, ns1__innercomplexGsoap2 *const*, const char *);
SOAP_FMAC3 ns1__innercomplexGsoap2 ** SOAP_FMAC4 soap_in_PointerTons1__innercomplexGsoap2(struct soap*, const char*, ns1__innercomplexGsoap2 **, const char*);

#define soap_write_PointerTons1__innercomplexGsoap2(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__innercomplexGsoap2(soap, data), 0) || soap_put_PointerTons1__innercomplexGsoap2(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__innercomplexGsoap2(struct soap*, ns1__innercomplexGsoap2 *const*, const char*, const char*);

#define soap_read_PointerTons1__innercomplexGsoap2(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__innercomplexGsoap2(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innercomplexGsoap2 ** SOAP_FMAC4 soap_get_PointerTons1__innercomplexGsoap2(struct soap*, ns1__innercomplexGsoap2 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__innercomplexGsoap1
#define SOAP_TYPE_PointerTons1__innercomplexGsoap1 (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__innercomplexGsoap1(struct soap*, ns1__innercomplexGsoap1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__innercomplexGsoap1(struct soap*, const char *, int, ns1__innercomplexGsoap1 *const*, const char *);
SOAP_FMAC3 ns1__innercomplexGsoap1 ** SOAP_FMAC4 soap_in_PointerTons1__innercomplexGsoap1(struct soap*, const char*, ns1__innercomplexGsoap1 **, const char*);

#define soap_write_PointerTons1__innercomplexGsoap1(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__innercomplexGsoap1(soap, data), 0) || soap_put_PointerTons1__innercomplexGsoap1(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__innercomplexGsoap1(struct soap*, ns1__innercomplexGsoap1 *const*, const char*, const char*);

#define soap_read_PointerTons1__innercomplexGsoap1(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__innercomplexGsoap1(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innercomplexGsoap1 ** SOAP_FMAC4 soap_get_PointerTons1__innercomplexGsoap1(struct soap*, ns1__innercomplexGsoap1 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__innersimpleGsoap10
#define SOAP_TYPE_PointerTons1__innersimpleGsoap10 (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__innersimpleGsoap10(struct soap*, ns1__innersimpleGsoap10 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__innersimpleGsoap10(struct soap*, const char *, int, ns1__innersimpleGsoap10 *const*, const char *);
SOAP_FMAC3 ns1__innersimpleGsoap10 ** SOAP_FMAC4 soap_in_PointerTons1__innersimpleGsoap10(struct soap*, const char*, ns1__innersimpleGsoap10 **, const char*);

#define soap_write_PointerTons1__innersimpleGsoap10(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__innersimpleGsoap10(soap, data), 0) || soap_put_PointerTons1__innersimpleGsoap10(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__innersimpleGsoap10(struct soap*, ns1__innersimpleGsoap10 *const*, const char*, const char*);

#define soap_read_PointerTons1__innersimpleGsoap10(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__innersimpleGsoap10(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innersimpleGsoap10 ** SOAP_FMAC4 soap_get_PointerTons1__innersimpleGsoap10(struct soap*, ns1__innersimpleGsoap10 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__innersimpleGsoap8
#define SOAP_TYPE_PointerTons1__innersimpleGsoap8 (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__innersimpleGsoap8(struct soap*, ns1__innersimpleGsoap8 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__innersimpleGsoap8(struct soap*, const char *, int, ns1__innersimpleGsoap8 *const*, const char *);
SOAP_FMAC3 ns1__innersimpleGsoap8 ** SOAP_FMAC4 soap_in_PointerTons1__innersimpleGsoap8(struct soap*, const char*, ns1__innersimpleGsoap8 **, const char*);

#define soap_write_PointerTons1__innersimpleGsoap8(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__innersimpleGsoap8(soap, data), 0) || soap_put_PointerTons1__innersimpleGsoap8(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__innersimpleGsoap8(struct soap*, ns1__innersimpleGsoap8 *const*, const char*, const char*);

#define soap_read_PointerTons1__innersimpleGsoap8(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__innersimpleGsoap8(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innersimpleGsoap8 ** SOAP_FMAC4 soap_get_PointerTons1__innersimpleGsoap8(struct soap*, ns1__innersimpleGsoap8 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__innersimpleGsoap6
#define SOAP_TYPE_PointerTons1__innersimpleGsoap6 (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__innersimpleGsoap6(struct soap*, ns1__innersimpleGsoap6 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__innersimpleGsoap6(struct soap*, const char *, int, ns1__innersimpleGsoap6 *const*, const char *);
SOAP_FMAC3 ns1__innersimpleGsoap6 ** SOAP_FMAC4 soap_in_PointerTons1__innersimpleGsoap6(struct soap*, const char*, ns1__innersimpleGsoap6 **, const char*);

#define soap_write_PointerTons1__innersimpleGsoap6(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__innersimpleGsoap6(soap, data), 0) || soap_put_PointerTons1__innersimpleGsoap6(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__innersimpleGsoap6(struct soap*, ns1__innersimpleGsoap6 *const*, const char*, const char*);

#define soap_read_PointerTons1__innersimpleGsoap6(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__innersimpleGsoap6(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innersimpleGsoap6 ** SOAP_FMAC4 soap_get_PointerTons1__innersimpleGsoap6(struct soap*, ns1__innersimpleGsoap6 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__innersimpleGsoap4
#define SOAP_TYPE_PointerTons1__innersimpleGsoap4 (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__innersimpleGsoap4(struct soap*, ns1__innersimpleGsoap4 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__innersimpleGsoap4(struct soap*, const char *, int, ns1__innersimpleGsoap4 *const*, const char *);
SOAP_FMAC3 ns1__innersimpleGsoap4 ** SOAP_FMAC4 soap_in_PointerTons1__innersimpleGsoap4(struct soap*, const char*, ns1__innersimpleGsoap4 **, const char*);

#define soap_write_PointerTons1__innersimpleGsoap4(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__innersimpleGsoap4(soap, data), 0) || soap_put_PointerTons1__innersimpleGsoap4(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__innersimpleGsoap4(struct soap*, ns1__innersimpleGsoap4 *const*, const char*, const char*);

#define soap_read_PointerTons1__innersimpleGsoap4(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__innersimpleGsoap4(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innersimpleGsoap4 ** SOAP_FMAC4 soap_get_PointerTons1__innersimpleGsoap4(struct soap*, ns1__innersimpleGsoap4 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__innersimpleGsoap2
#define SOAP_TYPE_PointerTons1__innersimpleGsoap2 (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__innersimpleGsoap2(struct soap*, ns1__innersimpleGsoap2 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__innersimpleGsoap2(struct soap*, const char *, int, ns1__innersimpleGsoap2 *const*, const char *);
SOAP_FMAC3 ns1__innersimpleGsoap2 ** SOAP_FMAC4 soap_in_PointerTons1__innersimpleGsoap2(struct soap*, const char*, ns1__innersimpleGsoap2 **, const char*);

#define soap_write_PointerTons1__innersimpleGsoap2(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__innersimpleGsoap2(soap, data), 0) || soap_put_PointerTons1__innersimpleGsoap2(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__innersimpleGsoap2(struct soap*, ns1__innersimpleGsoap2 *const*, const char*, const char*);

#define soap_read_PointerTons1__innersimpleGsoap2(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__innersimpleGsoap2(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns1__innersimpleGsoap2 ** SOAP_FMAC4 soap_get_PointerTons1__innersimpleGsoap2(struct soap*, ns1__innersimpleGsoap2 **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__normalizedString
#define SOAP_TYPE_xsd__normalizedString (7)
#endif

#define soap_default_xsd__normalizedString(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__normalizedString(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__normalizedString(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__normalizedString(struct soap*, const char*, char **, const char*);

#define soap_write_xsd__normalizedString(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__normalizedString(soap, data), 0) || soap_put_xsd__normalizedString(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__normalizedString(struct soap*, char *const*, const char*, const char*);

#define soap_read_xsd__normalizedString(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__normalizedString(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__normalizedString(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
