/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "file_constants.h"

namespace thriftTest {

const fileConstants g_file_constants;

fileConstants::fileConstants() {
}

} // namespace

