/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef fileSimple_CONSTANTS_H
#define fileSimple_CONSTANTS_H

#include "fileSimple_types.h"

namespace thriftTest {

class fileSimpleConstants {
 public:
  fileSimpleConstants();

};

extern const fileSimpleConstants g_fileSimple_constants;

} // namespace

#endif
