/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "fileSimple_constants.h"

namespace thriftTest {

const fileSimpleConstants g_fileSimple_constants;

fileSimpleConstants::fileSimpleConstants() {
}

} // namespace

