/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "performance_constants.h"

namespace thriftPerformance {

const performanceConstants g_performance_constants;

performanceConstants::performanceConstants() {
}

} // namespace

