/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef performance_CONSTANTS_H
#define performance_CONSTANTS_H

#include "performance_types.h"

namespace thriftPerformance {

class performanceConstants {
 public:
  performanceConstants();

};

extern const performanceConstants g_performance_constants;

} // namespace

#endif
